spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&autoReconnection=true
    username: scott
    password: tiger
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:      enabled: true
      location: ${java.io.tmpdir}
      max-file-size: 100MB      max-request-size: 20MB        
mybatis:
  configuration:
    lazy-loading-enabled: true
  type-aliases-package: com.example.notice
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
